name: Reusable Workflows

on: push

jobs:
  call-workflow:
    uses: the-iron-bank-of-braavos/reusable-workflow/.github/workflows/maven.build_and_push.yaml@main
    with:
      message: "Hello World"
