name: Reusable Workflows

on: push

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    uses: the-iron-bank-of-braavos/reusable-workflow/.github/workflows/maven-build-and-push.yaml@main
    with:
      message: "Hello World"
