name: Reusable Workflows

on: push

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    uses: the-iron-bank-of-braavos/reusable-workflow/.github/workflows/maven_build_and_push.yaml@v1
    with:
      message: "Hello World"
