name: Reusable Workflows

on: 
  push:
    branches:    
      - 'action-validator'

jobs:
  action-validator:
    uses: the-iron-bank-of-braavos/action-validator/.github/workflows/test.yml@main
    with:
      origin-repo: https://github.com/actions/github-script.git
      commit-sha: e3cbab9
      target-repo: the-iron-bank-of-braavos/test-cloned-action
