name: Reusable Workflows

on: push

jobs:
  call-workflow:
    steps:
      - name: POC Reusable Workflow
        uses: the-iron-bank-of-braavos/reusable-workflow/.github/workflows/maven.yml@main
        with:
          message: "Hello World"
